"""Graph builder service.

Interface 2 in the pipeline: creates and populates a standalone graph in Zep.
"""

import uuid
import time
import threading
from typing import Dict, Any, List, Optional, Callable
from dataclasses import dataclass
from datetime import datetime

from..config import Config
from..models.task import TaskManager, TaskStatus
from..utils.zep_paging import fetch_all_nodes, fetch_all_edges
from..utils.logger import get_logger
from.text_processor import TextProcessor

logger = get_logger('phoring.graph_builder')


@dataclass
class GraphInfo:
    """Lightweight graph statistics returned to API callers."""
    graph_id: str
    node_count: int
    edge_count: int
    entity_types: List[str]
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "graph_id": self.graph_id,
            "node_count": self.node_count,
            "edge_count": self.edge_count,
            "entity_types": self.entity_types,
        }


class GraphBuilderService:
    """Build and manage Zep knowledge graphs for simulation projects."""

    PREVIEW_MAX_NODES = 120
    PREVIEW_MAX_EDGES = 240
    
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or Config.ZEP_API_KEY
        if not self.api_key:
            raise ValueError("ZEP_API_KEY not yet configured")
        
        from zep_cloud.client import Zep
        self.client = Zep(api_key=self.api_key)
        self.task_manager = TaskManager()
    
    def build_graph_async(
        self,
        text: str,
        ontology: Dict[str, Any],
        graph_name: str = "Phoring Graph",
        chunk_size: int = 500,
        chunk_overlap: int = 50,
        batch_size: int = 3
    ) -> str:
        """Run graph construction asynchronously and return the task ID.

        Args:
            text: Source text to ingest.
            ontology: Ontology generated by interface 1.
            graph_name: Human-friendly graph name.
            chunk_size: Text chunk size for ingestion.
            chunk_overlap: Overlap between chunks.
            batch_size: Number of chunks sent per Zep batch call.

        Returns:
            Task ID for polling progress and result.
        """
        # Create task
        task_id = self.task_manager.create_task(
            task_type="graph_build",
            metadata={
                "graph_name": graph_name,
                "chunk_size": chunk_size,
                "text_length": len(text),
            }
        )
        
        # Background thread to run the build
        thread = threading.Thread(
            target=self._build_graph_worker,
            args=(task_id, text, ontology, graph_name, chunk_size, chunk_overlap, batch_size)
        )
        thread.daemon = True
        thread.start()
        
        return task_id
    
    def _build_graph_worker(
        self,
        task_id: str,
        text: str,
        ontology: Dict[str, Any],
        graph_name: str,
        chunk_size: int,
        chunk_overlap: int,
        batch_size: int
    ):
        """Graph build worker thread."""
        try:
            self.task_manager.update_task(
                task_id,
                status=TaskStatus.PROCESSING,
                progress=5,
                message="Starting graph build..."
            )
            
            # 1. Create graph
            graph_id = self.create_graph(graph_name)
            self.task_manager.update_task(
                task_id,
                progress=10,
                message=f"Graph created: {graph_id}"
            )
            
            # 2. Apply ontology settings
            self.set_ontology(graph_id, ontology)
            self.task_manager.update_task(
                task_id,
                progress=15,
                message="Ontology applied"
            )
            
            # 3. Split text into chunks
            chunks = TextProcessor.split_text(text, chunk_size, chunk_overlap)
            total_chunks = len(chunks)
            self.task_manager.update_task(
                task_id,
                progress=20,
                message=f"Text split into {total_chunks} chunks"
            )
            
            # 4. Ingest data in batches
            episode_uuids = self.add_text_batches(
                graph_id, chunks, batch_size,
                lambda msg, prog: self.task_manager.update_task(
                    task_id,
                    progress=20 + int(prog * 0.4), # 20-60%
                    message=msg
                )
            )
            
            # 5. Wait for Zep processing to complete
            self.task_manager.update_task(
                task_id,
                progress=60,
                message="Waiting for Zep ingestion to finish..."
            )
            
            self._wait_for_episodes(
                episode_uuids,
                lambda msg, prog: self.task_manager.update_task(
                    task_id,
                    progress=60 + int(prog * 0.3), # 60-90%
                    message=msg
                ),
                graph_id=graph_id
            )
            
            # 6. Collect graph summary data.
            self.task_manager.update_task(
                task_id,
                progress=90,
                message="Collecting graph statistics..."
            )
            
            graph_info = self.get_graph_info(graph_id)
            
            # Mark task as complete
            self.task_manager.complete_task(task_id, {
                "graph_id": graph_id,
                "graph_info": graph_info.to_dict(),
                "chunks_processed": total_chunks,
            })
            
        except Exception as e:
            import traceback
            error_msg = f"{str(e)}\n{traceback.format_exc()}"
            self.task_manager.fail_task(task_id, error_msg)
    
    def create_graph(self, name: str) -> str:
        """Create Zep graph (sync method)."""
        graph_id = f"phoring_{uuid.uuid4().hex[:16]}"
        
        self.client.graph.create(
            graph_id=graph_id,
            name=name,
            description="Phoring Social Simulation Graph"
        )
        
        return graph_id
    
    def set_ontology(self, graph_id: str, ontology: Dict[str, Any]):
        """Apply ontology entity and edge schemas to a graph."""
        import warnings
        from pydantic import Field
        from zep_cloud.external_clients.ontology import EntityModel, EntityText, EdgeModel
        
        # Suppress Pydantic v2 Field(default=None) warnings
        # Auto-created by Zep SDK; safe to ignore
        warnings.filterwarnings('ignore', category=UserWarning, module='pydantic')
        
        # Zep reserved attribute names
        RESERVED_NAMES = {'uuid', 'name', 'group_id', 'name_embedding', 'summary', 'created_at'}
        
        def safe_attr_name(attr_name: str) -> str:
            """Rename reserved attribute names to avoid Zep schema conflicts."""
            if attr_name.lower() in RESERVED_NAMES:
                return f"entity_{attr_name}"
            return attr_name
        
        # Create entity types
        entity_types = {}
        for entity_def in ontology.get("entity_types", []):
            name = entity_def["name"]
            description = entity_def.get("description", f"A {name} entity.")
            
            # Create attribute types (Pydantic v2)
            attrs = {"__doc__": description}
            annotations = {}
            
            for attr_def in entity_def.get("attributes", []):
                attr_name = safe_attr_name(attr_def["name"]) # Rename if reserved
                attr_desc = attr_def.get("description", attr_name)
                # Use Zep API Field description
                attrs[attr_name] = Field(description=attr_desc, default=None)
                annotations[attr_name] = Optional[EntityText] # Attribute type
            
            attrs["__annotations__"] = annotations
            
            # Create entity class dynamically
            entity_class = type(name, (EntityModel,), attrs)
            entity_class.__doc__ = description
            entity_types[name] = entity_class
        
        # Create edge types
        edge_definitions = {}
        for edge_def in ontology.get("edge_types", []):
            name = edge_def["name"]
            description = edge_def.get("description", f"A {name} relationship.")
            
            # Create attribute types for edge
            attrs = {"__doc__": description}
            annotations = {}
            
            for attr_def in edge_def.get("attributes", []):
                attr_name = safe_attr_name(attr_def["name"]) # Rename if reserved
                attr_desc = attr_def.get("description", attr_name)
                # Use Zep API Field description
                attrs[attr_name] = Field(description=attr_desc, default=None)
                annotations[attr_name] = Optional[str] # Attribute string type
            
            attrs["__annotations__"] = annotations
            
            # Create edge class dynamically
            class_name = ''.join(word.capitalize() for word in name.split('_'))
            edge_class = type(class_name, (EdgeModel,), attrs)
            edge_class.__doc__ = description
            
            # Build source_targets
            source_targets = []
            from zep_cloud import EntityEdgeSourceTarget
            for st in edge_def.get("source_targets", []):
                source_targets.append(
                    EntityEdgeSourceTarget(
                        source=st.get("source", "Entity"),
                        target=st.get("target", "Entity")
                    )
                )
            
            if source_targets:
                edge_definitions[name] = (edge_class, source_targets)
        
        # Call Zep API to apply ontology settings
        if entity_types or edge_definitions:
            self.client.graph.set_ontology(
                graph_ids=[graph_id],
                entities=entity_types if entity_types else None,
                edges=edge_definitions if edge_definitions else None,
            )
    
    def add_text_batches(
        self,
        graph_id: str,
        chunks: List[str],
        batch_size: int = 3,
        progress_callback: Optional[Callable] = None
    ) -> List[str]:
        """Ingest chunked text in batches and return created episode UUIDs."""
        episode_uuids = []
        total_chunks = len(chunks)
        
        for i in range(0, total_chunks, batch_size):
            batch_chunks = chunks[i:i + batch_size]
            batch_num = i // batch_size + 1
            total_batches = (total_chunks + batch_size - 1) // batch_size
            
            if progress_callback:
                progress = (i + len(batch_chunks)) / total_chunks
                progress_callback(
                    f"Ingesting batch {batch_num}/{total_batches} ({len(batch_chunks)} chunks)...",
                    progress
                )
            
            # Build episode data
            from zep_cloud import EpisodeData
            episodes = [
                EpisodeData(data=chunk, type="text")
                for chunk in batch_chunks
            ]
            
            # Send to Zep
            try:
                batch_result = self.client.graph.add_batch(
                    graph_id=graph_id,
                    episodes=episodes
                )
                
                # Collect returned episode UUIDs
                if batch_result and isinstance(batch_result, list):
                    for ep in batch_result:
                        ep_uuid = getattr(ep, 'uuid_', None) or getattr(ep, 'uuid', None)
                        if ep_uuid:
                            episode_uuids.append(ep_uuid)
                
                # Rate limit to avoid API throttling
                time.sleep(1)
                
            except Exception as e:
                if progress_callback:
                    progress_callback(f"batch {batch_num} failed: {str(e)}", 0)
                raise
        
        return episode_uuids
    
    def _wait_for_episodes(
        self,
        episode_uuids: List[str],
        progress_callback: Optional[Callable] = None,
        timeout: int = 300,
        graph_id: Optional[str] = None
    ):
        """Poll episodes until ingestion is processed or timeout is reached."""
        if not episode_uuids:
            if progress_callback:
                progress_callback("No episodes to wait for", 1.0)
            return

        start_time = time.time()
        pending_episodes = set(episode_uuids)
        completed_count = 0
        total_episodes = len(episode_uuids)

        if progress_callback:
            progress_callback(f"Waiting for {total_episodes} episodes to be processed...", 0)

        while pending_episodes:
            elapsed = int(time.time() - start_time)

            if elapsed > timeout:
                if progress_callback:
                    progress_callback(
                        f"Episode processing timeout after {elapsed}s: completed {completed_count}/{total_episodes}",
                        completed_count / total_episodes
                    )
                break

            # Early exit: if graph already has nodes, ingestion is sufficiently complete
            if graph_id and elapsed > 30 and elapsed % 30 < 3:
                try:
                    nodes = fetch_all_nodes(self.client, graph_id)
                    if nodes:
                        if progress_callback:
                            progress_callback(
                                f"Graph has {len(nodes)} nodes — ingestion complete",
                                1.0
                            )
                        break
                except Exception:
                    pass

            # Check each episode processing status
            for ep_uuid in list(pending_episodes):
                try:
                    episode = self.client.graph.episode.get(uuid_=ep_uuid)
                    is_processed = getattr(episode, 'processed', False)

                    if is_processed:
                        pending_episodes.remove(ep_uuid)
                        completed_count += 1

                except Exception:
                    pass

            if progress_callback:
                progress_callback(
                    f"Zep processing: {completed_count}/{total_episodes} done, {len(pending_episodes)} pending ({elapsed}s)",
                    completed_count / total_episodes if total_episodes > 0 else 0
                )

            if pending_episodes:
                time.sleep(3)

        if progress_callback:
            progress_callback(f"Processing complete: {completed_count}/{total_episodes}", 1.0)
    
    def get_graph_info(self, graph_id: str) -> GraphInfo:
        """Fetch node/edge totals and inferred entity label types (lightweight)."""
        nodes = fetch_all_nodes(self.client, graph_id)
        edges = fetch_all_edges(self.client, graph_id)

        entity_types = set()
        for node in nodes:
            labels = getattr(node, 'labels', None) or []
            for label in labels:
                if label not in ("Entity", "Node"):
                    entity_types.add(label)

        return GraphInfo(
            graph_id=graph_id,
            node_count=len(nodes),
            edge_count=len(edges),
            entity_types=list(entity_types)
        )
    
    def get_graph_data(self, graph_id: str) -> Dict[str, Any]:
        """Return full graph payload including node and edge metadata."""
        nodes = fetch_all_nodes(self.client, graph_id)
        edges = fetch_all_edges(self.client, graph_id)

        return self._build_graph_payload(
            graph_id=graph_id,
            nodes=nodes,
            edges=edges,
            is_preview=False,
            is_complete=True,
            status="completed",
        )

    def get_graph_preview(self, graph_id: str) -> Dict[str, Any]:
        """Return a capped graph preview that is safe to poll during graph builds."""
        nodes = fetch_all_nodes(self.client, graph_id)
        edges = fetch_all_edges(self.client, graph_id)

        preview_nodes = nodes[:self.PREVIEW_MAX_NODES]
        preview_node_ids = {
            getattr(node, 'uuid_', None) or getattr(node, 'uuid', '')
            for node in preview_nodes
        }
        preview_edges = [
            edge for edge in edges
            if (getattr(edge, 'source_node_uuid', None) or '') in preview_node_ids
            and (getattr(edge, 'target_node_uuid', None) or '') in preview_node_ids
        ][:self.PREVIEW_MAX_EDGES]

        return self._build_graph_payload(
            graph_id=graph_id,
            nodes=preview_nodes,
            edges=preview_edges,
            is_preview=True,
            is_complete=False,
            status="building",
            total_node_count=len(nodes),
            total_edge_count=len(edges),
        )

    def _build_graph_payload(
        self,
        graph_id: str,
        nodes: List[Any],
        edges: List[Any],
        *,
        is_preview: bool,
        is_complete: bool,
        status: str,
        total_node_count: Optional[int] = None,
        total_edge_count: Optional[int] = None,
    ) -> Dict[str, Any]:
        """Serialize node and edge objects into a graph payload."""

        # Build node UUID-to-name map (defensive)
        node_map = {}
        for node in nodes:
            nid = getattr(node, 'uuid_', None) or getattr(node, 'uuid', '')
            node_map[nid] = getattr(node, 'name', None) or ''
        
        nodes_data = []
        for node in nodes:
            created_at = getattr(node, 'created_at', None)
            if created_at:
                created_at = str(created_at)
            
            nodes_data.append({
                "uuid": getattr(node, 'uuid_', None) or getattr(node, 'uuid', ''),
                "name": getattr(node, 'name', None) or '',
                "labels": getattr(node, 'labels', None) or [],
                "summary": getattr(node, 'summary', None) or '',
                "attributes": getattr(node, 'attributes', None) or {},
                "created_at": created_at,
            })
        
        edges_data = []
        for edge in edges:
            created_at = getattr(edge, 'created_at', None)
            valid_at = getattr(edge, 'valid_at', None)
            invalid_at = getattr(edge, 'invalid_at', None)
            expired_at = getattr(edge, 'expired_at', None)
            
            episodes = getattr(edge, 'episodes', None) or getattr(edge, 'episode_ids', None)
            if episodes and not isinstance(episodes, list):
                episodes = [str(episodes)]
            elif episodes:
                episodes = [str(e) for e in episodes]
            
            edge_name = getattr(edge, 'name', None) or ''
            fact_type = getattr(edge, 'fact_type', None) or edge_name
            source_uuid = getattr(edge, 'source_node_uuid', None) or ''
            target_uuid = getattr(edge, 'target_node_uuid', None) or ''
            
            edges_data.append({
                "uuid": getattr(edge, 'uuid_', None) or getattr(edge, 'uuid', ''),
                "name": edge_name,
                "fact": getattr(edge, 'fact', None) or '',
                "fact_type": fact_type,
                "source_node_uuid": source_uuid,
                "target_node_uuid": target_uuid,
                "source_node_name": node_map.get(source_uuid, ''),
                "target_node_name": node_map.get(target_uuid, ''),
                "attributes": getattr(edge, 'attributes', None) or {},
                "created_at": str(created_at) if created_at else None,
                "valid_at": str(valid_at) if valid_at else None,
                "invalid_at": str(invalid_at) if invalid_at else None,
                "expired_at": str(expired_at) if expired_at else None,
                "episodes": episodes or [],
            })
        
        if total_node_count is None:
            total_node_count = len(nodes_data)
        if total_edge_count is None:
            total_edge_count = len(edges_data)

        return {
            "graph_id": graph_id,
            "nodes": nodes_data,
            "edges": edges_data,
            "node_count": len(nodes_data),
            "edge_count": len(edges_data),
            "total_node_count": total_node_count,
            "total_edge_count": total_edge_count,
            "is_preview": is_preview,
            "is_complete": is_complete,
            "status": status,
            "last_updated": datetime.utcnow().isoformat() + "Z",
        }
    
    def delete_graph(self, graph_id: str):
        """Delete a graph from Zep."""
        self.client.graph.delete(graph_id=graph_id)

